

# Run the following prior:

# 1- FOR MONGO ROOT PASSWORD:
#   echo "<password for mongo>" | docker secret create mongo_root_password -

# 2- FOR TLS KEYS & CERTS [api service]: 
#   add valid certs to the __certs folder


version: '3.8'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - mongodb
    volumes:
      - ./cdn:/usr/share/nginx/html/cdn
    ports:
      - 8080:80
    networks:
      - app_network
  
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
    secrets:
      - mongo_root_password
  
  api:
    build: ../api
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    depends_on:
      - mongodb
    networks:
      - app_network
    ports:
      # Map localhost machine port 3000 to app port 4000
      - 3000:4000
    volumes:
      - ../__certs:/etc/ssl
    environment:
      # ... Add env
      NODE_ENV: development
      BC_PORT: 4000
      BC_HTTPS: false
      BC_PRIVATE_KEY: /etc/ssl/bookcars.com.key
      BC_CERTIFICATE: /etc/ssl/bookcars.com.crt
      BC_DB_HOST: mongodb #BC_DB_HOST: mongodb
      BC_DB_PORT: 27017
      BC_DB_SSL: false
      BC_DB_SSL_KEY: /etc/ssl/bookcars.com.key
      BC_DB_SSL_CERT: /etc/ssl/bookcars.com.crt
      BC_DB_SSL_CA: /etc/ssl/bookcars.com.ca.pem
      BC_DB_DEBUG: false
      BC_DB_APP_NAME: bookcars
      BC_DB_AUTH_SOURCE: admin
      BC_DB_USERNAME: admin #BC_DB_USERNAME: SHOULD MATCH MONGODB INSTANCE
      BC_DB_PASSWORD_FILE: /run/secrets/mongo_root_password # Uses Docker Secrets path. SHOULD MATCH MONGODB INSTANCE
      BC_DB_NAME: bookcars
      BC_JWT_SECRET: SECRET
      BC_JWT_EXPIRE_AT: 86400
      BC_TOKEN_EXPIRE_AT: 86400
      BC_SMTP_HOST: in-v3.mailjet.com
      BC_SMTP_PORT: 587
      BC_SMTP_USER: USER # INPUT
      BC_SMTP_PASS: PASSWORD # INPUT
      BC_SMTP_FROM: admin@bookcars.com # INPUT
      BC_ADMIN_EMAIL: admin@bookcars.com # INPUT
      BC_CDN_USERS: /var/www/cdn/bookcars/users
      BC_CDN_TEMP_USERS: /var/www/cdn/bookcars/temp/users
      BC_CDN_CARS: /var/www/cdn/bookcars/cars
      BC_CDN_TEMP_CARS: /var/www/cdn/bookcars/temp/cars
      BC_DEFAULT_LANGUAGE: en
      BC_BACKOFFICE_HOST: http://backoffice:3002/
      BC_FRONTEND_HOST: http://frontoffice:3001/
      BC_MINIMUM_AGE: 21
      BC_EXPO_ACCESS_TOKEN: TOKEN # INPUT

  frontend:
    build: ../frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    depends_on:
      - mongodb
    networks:
      - app_network
    ports:
        # Map localhost machine port 3001 to app port 4000
      - 3001:80
    environment:
      PORT: 80 #edited from 3001
      REACT_APP_NODE_ENV: development
      REACT_APP_BC_API_HOST: http://api:3000
      REACT_APP_BC_RECAPTCHA_SITE_KEY: GOOGLE_RECAPTCHA_SITE_KEY # INPUT
      REACT_APP_BC_DEFAULT_LANGUAGE: en
      REACT_APP_BC_PAGE_SIZE: 30
      REACT_APP_BC_CARS_PAGE_SIZE: 15
      REACT_APP_BC_BOOKINGS_PAGE_SIZE: 20
      REACT_APP_BC_CDN_USERS: http://nginx/cdn/bookcars/users
      REACT_APP_BC_CDN_CARS: http://nginx/cdn/bookcars/cars
      REACT_APP_BC_COMAPANY_IMAGE_WIDTH: 60
      REACT_APP_BC_COMAPANY_IMAGE_HEIGHT: 30
      REACT_APP_BC_CAR_IMAGE_WIDTH: 300
      REACT_APP_BC_CAR_IMAGE_HEIGHT: 200
      REACT_APP_BC_APP_TYPE: frontend
      REACT_APP_BC_MINIMUM_AGE: 21

  backoffice:
    build: ../backoffice
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    depends_on:
      - mongodb
    networks:
      - app_network
    ports:
      # Map localhost machine port 3002 to app port 80
      - 3002:80
    environment:
      PORT: 80 #edited from 3000
      REACT_APP_NODE_ENV: development
      REACT_APP_BC_API_HOST: http://api:3000
      REACT_APP_BC_DEFAULT_LANGUAGE: en
      REACT_APP_BC_PAGE_SIZE: 30
      REACT_APP_BC_CARS_PAGE_SIZE: 15
      REACT_APP_BC_BOOKINGS_PAGE_SIZE: 20
      REACT_APP_BC_CDN_USERS: http://nginx/cdn/bookcars/users
      REACT_APP_BC_CDN_TEMP_USERS: http://nginx/cdn/bookcars/temp/users
      REACT_APP_BC_CDN_CARS: http://nginx/cdn/bookcars/cars
      REACT_APP_BC_CDN_TEMP_CARS: http://nginx/cdn/bookcars/temp/cars
      REACT_APP_BC_COMAPANY_IMAGE_WIDTH: 60
      REACT_APP_BC_COMAPANY_IMAGE_HEIGHT: 30
      REACT_APP_BC_CAR_IMAGE_WIDTH: 300
      REACT_APP_BC_CAR_IMAGE_HEIGHT: 200
      REACT_APP_BC_APP_TYPE: backoffice
      REACT_APP_BC_MINIMUM_AGE: 21

networks:
  app-network:
    driver: overlay

volumes:
  mongodb_data:

secrets:
  mongo_root_password:
    external: true
